platform :ios, '9.0'
target 'BatMan' do
pod 'YYKit'
pod 'AFNetworking', '~> 3.1.0'
pod 'MJRefresh', '~> 3.1.12'
pod 'SDWebImage', '~> 4.0.0-beta2'
pod 'SVProgressHUD', '~> 2.0.4'
pod 'MJExtension', '~> 3.0.13'
end

